In [1]:
import torch
from torch import nn
from torch import Tensor

In [3]:
conv1 = nn.Conv1d(1, 3, 2)

In [45]:
conv2 = nn.Conv2d(1, 1, 3)

In [31]:
one_d = Tensor([1., 2., 3., 4., 5.])

In [43]:
two_d = Tensor([[1., 1., 1., 0., 0.],
                [0., 1., 1., 1., 0.],
                [0., 0., 1., 1., 1.],
                [0., 0., 1., 1., 0.],
                [0., 1., 1., 0., 0.]
               ])

In [42]:
one_d.unsqueeze(-1).unsqueeze(-1)

tensor([[[1.]],

        [[2.]],

        [[3.]],

        [[4.]],

        [[5.]]])

In [33]:
conv1(one_d)

RuntimeError: Expected 3-dimensional input for 3-dimensional weight [3, 1, 2], but got 1-dimensional input of size [5] instead

In [28]:
two_d.shape

torch.Size([3, 4, 1])

In [30]:
two_d.unsqueeze(1).shape

torch.Size([3, 1, 4, 1])

In [52]:
conv2.weight.data = Tensor([[[
          [1., 0., 1.],
          [0., 1., 0.],
          [1., 0., 1.]]]])

In [53]:
new_conv2 = conv2.weight.copy_(Tensor([[[
          [1., 0., 1.],
          [0., 1., 0.],
          [1., 0., 1.]]]]))

Parameter containing:
tensor([[[[1., 0., 1.],
          [0., 1., 0.],
          [1., 0., 1.]]]], requires_grad=True)

In [54]:
two_d_one = two_d.unsqueeze(0).unsqueeze(0)
two_d_one

tensor([[[[1., 1., 1., 0., 0.],
          [0., 1., 1., 1., 0.],
          [0., 0., 1., 1., 1.],
          [0., 0., 1., 1., 0.],
          [0., 1., 1., 0., 0.]]]])

In [55]:
conv2(two_d_one)

tensor([[[[3.8097, 2.8097, 3.8097],
          [1.8097, 3.8097, 2.8097],
          [1.8097, 2.8097, 3.8097]]]], grad_fn=<MkldnnConvolutionBackward>)

In [57]:
two_d_two = two_d.unsqueeze(-1).unsqueeze(-1)


In [58]:
conv2(two_d_two)

RuntimeError: Given groups=1, weight of size [1, 1, 3, 3], expected input[5, 5, 1, 1] to have 1 channels, but got 5 channels instead

In [1]:
import pandas as pd

In [2]:
old_path = '../../data/eval1_unlabelled.tsv'
new_path = '../../data/eval1_wideresnet_01.tsv'

In [4]:
data = pd.read_csv(old_path, sep='\t', encoding='utf-8',
                  names=['qid', 'query', 'passage', 'label', 'pid'])